# Generated by Django 4.1 on 2022-10-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0002_remove_photo_id_photo_photo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
